# Read the documentation: https://github.com/acseo/TypesenseBundle/blob/master/README.md
acseo_typesense:
    typesense:
        url: '%env(TYPESENSE_URL)%'
        key: '%env(TYPESENSE_KEY)%'
        # Optional : add prefix to all collection names in Typesense
        #collection_prefix: 'app_'
    # Collection settings
    collections:
        scores:
            entity: 'App\Library\Entity\Score'
            default_sorting_field: createdAt
            symbols_to_index: ['@']
            fields:
                id:
                    name: id
                    type: primary
#                sortable_id:
#                    entity_attribute: id
#                    name: sortable_id
#                    type: string
                title:
                    name: title
                    type: string
                createdAt:
                    name: createdAt
                    type: datetime

