services:
  db:
    container_name: score-lib-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: score-lib
      MYSQL_DATABASE: score-lib
      MYSQL_USER: score-lib
      MYSQL_PASSWORD: score-lib
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - scorelib

  php:
    container_name: score-lib-php
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug,coverage
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - .:/var/www
    depends_on:
      - db
      - search
    networks:
      - scorelib

  search:
    container_name: score-lib-search
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./var/typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    networks:
      - scorelib

  search-dashboard:
    container_name: score-lib-search-dashboard
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    ports:
      - "8118:80"
    networks:
      - scorelib

networks:
  scorelib:
    name: scorelib
