controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    options: {expose: true}

library_controllers:
    resource:
        path: ../src/Library/Controller/
        namespace: App\Library\Controller
    type: attribute
    options: {expose: true}
